# Generated by Django 2.1.7 on 2019-04-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_logincred'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincred',
            name='firstName',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logincred',
            name='lastName',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
    ]
